// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvavhbkzfbzexczfpkif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2YXZoYmt6ZmJ6ZXhjemZwa2lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMTc3MTksImV4cCI6MjA3NDc5MzcxOX0.1THVUin_egO3ODSa_5vntetjRzSU9r5l8_FoiCIx4YE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});